### ISSUE TITLE
Looper issues 

### ISSUE THREAD

**Issue by educastlan** [polyeffects/digit_ui#2] opened 2021-03-27 11:43 UTC
Assigning a foot pedal to a loop function works fine, however if you delete that loop and press that same footswitch the pedal completely freezes.

the delay button on the looper doesn't seem to work (might be user error). 

not sure if this is by design, but by reading up on the EDP, replace and substitute should be momentary switches but on beebo are latching.

Also not a bug but I think it would be more useful, in the cycles readout, to see how many cycles that particular loop has instead of how long the cycle is, hope that makes sense. 

When you delete a loop, it does not delete the selected loop, it deletes the last loop always

In case it matters in some way, my unit is a Digit S.No. 35
If you need me to clarify anything please let me know.

**Comment by loki42** [comment] 2021-03-29 08:12
Next version there will be a menu screen on assigning to MIDI / foot switch which will ask if you want it to be latching or momentary for all actions. 

Delete deleted the last loop by design, not sure how to make that clearer in the UI.  Others sound like bugs that I'll look into.

**Closed** 2021-03-31 05:17 UTC
